# DoE | Planejando Experimentos com Python

Nesta atividade, vamos gerar diferentes planos experimentais.

Para tal, utilizaremos a biblioteca `pyDOE2` ([informações](https://pypi.org/project/pyDOE2/) e [documentação](https://pythonhosted.org/pyDOE/)).

O Colab não vem com essa biblioteca pré-instalada, então Vamos começar instalando essa biblioteca usando o `pip`.

### Antes de começar: Instale o `pyDOE2` usando o pip.
Dica: No Colab, temos que colocar um sinal de `!` antes do `pip`, assim: `!pip`

In [1]:
!pip install pyDOE2

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for pyDOE2: filename=pyDOE2-1.3.0-py3-none-any.whl size=25553 sha256=7ba575362472604c59db24ca20ee1bd5e4f962055452af7ea0492e86ce4815ab
  Stored in directory: c:\users\99769242\appdata\local\pip\cache\wheels\a7\de\26\98f9a9ff6082bdd6f2c003c6471f0fa7536b1ddd24dc2997e9
Successfully built pyDOE2


Após instalar a biblioteca, importe-a e importe também as suas dependências `numpy`e `scipy`:

In [2]:
import numpy as np
import scipy as sp

# Geração de Matrizes de Projeto

O pyDOE2 permite criar matrizes de projeto que definem as configurações dos fatores experimentais a serem testados. A  biblioteca suporta vários tipos de matrizes, incluindo:

* **Fatoriais completos**: gera uma matriz de todos os possíveis níveis de todos os fatores.
* **Fatoriais fracionados**: gera uma matriz de uma fração dos níveis possíveis para todos os fatores, reduzindo o número total de configurações a serem testadas.

Vamos praticar ao longo das atividades a seguir:

### Atividade 1: Fatorial Completo de 3 Fatores e 2 Níveis

Nesta abordagem pode haver **apenas dois níveis** por fator.
Esses valores serão representados pelos valores `1` e `-1`.

Dica: Para Fatorial Completo de 2 Níveis, utilizaremos a função `ff2n`.

In [3]:
import pyDOE2 as doe

In [5]:
design1 = doe.ff2n(3)

print(len(design1))
design1

8


array([[-1., -1., -1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1.,  1.,  1.]])

**PERGUNTA:** Quantas configurações serão testadas no experimento?

>   **RESPOSTA:** 8

## Atividade 2: Fatorial Completo (mais de 2 níveis)
Nesta abordagem, pode haver **mais que apenas 2 níveis por fator**, permitindo maior flexibilidade. No entanto, isso irá aumentar a complexidade do experimento.

Crie um Design Fatorial Completo com 3 fatores, com a seguinte configuração:
* O primeiro fator tem 3 níveis;
* O segundo fator tem 2 níveis;
* O terceiro fator tem 4 níveis;

Dica: para Fatorial Completo Geral, utilizaremos a função `fullfact`.



In [7]:
# Definindo o número de níveis para cada fator
levels = [3, 2, 4]  # 3 níveis para o fator 1, 2 níveis para o fator 2 e 4 níveis para o fator 3

# Gerando o design fatorial completo
design2 = doe.fullfact(levels)

# Mostrando a matriz de design
design2

array([[0., 0., 0.],
       [1., 0., 0.],
       [2., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [2., 1., 0.],
       [0., 0., 1.],
       [1., 0., 1.],
       [2., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [2., 1., 1.],
       [0., 0., 2.],
       [1., 0., 2.],
       [2., 0., 2.],
       [0., 1., 2.],
       [1., 1., 2.],
       [2., 1., 2.],
       [0., 0., 3.],
       [1., 0., 3.],
       [2., 0., 3.],
       [0., 1., 3.],
       [1., 1., 3.],
       [2., 1., 3.]])

**PERGUNTA:** Quantas configurações serão testadas no experimento?

In [8]:
print(len(design2))

24


  > **RESPOSTA:** 24

## Atividade 3: Fatorial Completo de 3 Fatores e 2 Níveis (parte 2)

Suponha que para a produção de um bolo pronto, desejemos testar os seguintes fatores e níveis:

**Fator 1 | Farinha:**
Tipo 1 ou Tipo 2

**Fator 2 | Quantidade de Fermento:**
24mg ou 36mg

**Fator 3 | Temperatura:**
140ºC ou 180ºC

**INSTRUÇÕES:**

**A.** Gere o plano experimental de fatorial completo utilizando o pyDOE2

**B.** A partir do resultado, crie um DataFrame com o plano expermental, substituindo os valores *1* e *-1* pelos valores reais a serem testados.

In [9]:
# Gerando o design fatorial completo de 2 níveis para 3 fatores
design = doe.ff2n(3)
print(design)

[[-1. -1. -1.]
 [ 1. -1. -1.]
 [-1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]
 [ 1. -1.  1.]
 [-1.  1.  1.]
 [ 1.  1.  1.]]


In [12]:
import pandas as pd

# Convertendo o design para um DataFrame
df = pd.DataFrame(design, columns=["Farinha", "Fermento", "Temperatura"])

# Substituindo os valores para a coluna "Farinha"
df["Farinha"] = df["Farinha"].replace({-1: "Tipo 1", 1: "Tipo 2"})

# Substituindo os valores para a coluna "Fermento"
df["Fermento"] = df["Fermento"].replace({-1: "24mg", 1: "36mg"})

# Substituindo os valores para a coluna "Temperatura"
df["Temperatura"] = df["Temperatura"].replace({-1: "140ºC", 1: "180ºC"})

df

Farinha Fermento Temperatura
0  Tipo 1     24mg       140ºC
1  Tipo 2     24mg       140ºC
2  Tipo 1     36mg       140ºC
3  Tipo 2     36mg       140ºC
4  Tipo 1     24mg       180ºC
5  Tipo 2     24mg       180ºC
6  Tipo 1     36mg       180ºC
7  Tipo 2     36mg       180ºC

In [ ]:
# seu código

## Atividade 4: Fatorial Fracionado de 3 Fatores e 2 Níveis

Suponha que antes de rodar um experimento mais complexo como o proposto anteriormente, você decida fazer uma rodada preliminar e mais simples. Assim, você decidirá se os Fatores escolhidos (Tipo da Farinha, Quantidade de Fermento e Temperatura do Forno) aparentam ter de fato algum efeito significativo sobre o sabor do bolo.

Para tal, você decidiu optar por um desenho experimental com apenas 4 experimentos, em vez dos 8 experimentos anteriores.

### Atividade 4.1: Gere um desenho Fatorial Fracionado de 3 Fatores e 2 Níveis

In [29]:
# Gerando o design fatorial fracionado
# A string 'ABC' indica um design fracionado com 3 fatores, sem interações de alta ordem.
design = doe.fracfact('A B AB')

design

array([[-1., -1.,  1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1.,  1.]])

### Atividade 4.2: Crie um DataFrame com os valores das variáveis a serem testadas no experimento anterior

In [30]:
import pandas as pd

# Convertendo o design para um DataFrame
df_frac = pd.DataFrame(design, columns=["Farinha", "Fermento", "Temperatura"])

# Substituindo os valores para a coluna "Farinha"
df_frac["Farinha"] = df_frac["Farinha"].replace({-1.0: "Tipo 1", 1.0: "Tipo 2"})

# Substituindo os valores para a coluna "Fermento"
df_frac["Fermento"] = df_frac["Fermento"].replace({-1.0: "24mg", 1.0: "36mg"})

# Substituindo os valores para a coluna "Temperatura"
df_frac["Temperatura"] = df_frac["Temperatura"].replace({-1.0: "140ºC", 1.0: "180ºC"})

df_frac

Farinha Fermento Temperatura
0  Tipo 1     24mg       180ºC
1  Tipo 2     24mg       140ºC
2  Tipo 1     36mg       140ºC
3  Tipo 2     36mg       180ºC

### Atividade 4.3: Invertendo as combinações do Fatorial Fracionado

Suponha que uma colega de equipe com mais experiência em produtos dessa categoria pede que no plano experimental seja contemplada uma combinação específica, não prevista inicialmente. A combinação é a seguinte:

**Farinha:** Tipo 2

**Quantidade de Fermento:** 36mg

**Temperatura:** 180ºC

Adapte o plano experimental de forma que o número de combinações (unidades experimentais) se mantenha o mesmo (4), mas que seja possível testar a combinação proposta.

Dica: Consulte a documentação do pyDOE2 neste [link](https://pythonhosted.org/pyDOE/factorial.html)

In [31]:
# Gerando o complemento do design fatorial fracionado
# A string 'a b c' (em minúsculas) indica a geração da outra metade do fatorial fracionado.
design_complement = doe.fracfact('a b -ab')

# Convertendo para um DataFrame
df_complement = pd.DataFrame(design_complement, columns=["Farinha", "Fermento", "Temperatura"])

# Substituindo os valores
df_complement["Farinha"] = df_complement["Farinha"].replace({-1.0: "Tipo 1", 1.0: "Tipo 2"})
df_complement["Fermento"] = df_complement["Fermento"].replace({-1.0: "24mg", 1.0: "36mg"})
df_complement["Temperatura"] = df_complement["Temperatura"].replace({-1.0: "140ºC", 1.0: "180ºC"})

df_complement

Farinha Fermento Temperatura
0  Tipo 1     24mg       140ºC
1  Tipo 2     24mg       180ºC
2  Tipo 1     36mg       180ºC
3  Tipo 2     36mg       140ºC

## Atividade 5

Suponha que a rodada experimental inicial teve resultados bastante proveitosos e foi possível concluir que as Farinhas dos tipos 1 e 2 (ambas super premium) são praticamente iguais. Assim, optar-se-á pela Farinha do tipo 1, que tem um valor mais baixo.

Também percebeu-se que a temperatura de 140ºC foi insuficiente em todos os casos. Assim, decidiu-se testar as temperaturas de 160ºC e de 180ºC.

De modo geral, a rodada inicial correu bem e rapidamente. Por isso, a equipe resolveu incluir outros fatores que não haviam sido testados anteriormente.

Na segunda rodada, serão testados os seguintes fatores:

**A) Quantidade de Fermento:**
24mg ou 36mg

**B) Temperatura:**
160ºC ou 180ºC

**C) Tempo:**
35min ou 40min

**D) Ovos:**
3 ou 4

### Atividade 5.1: Faça uma estimativa de quantos testes seriam necessários para testar todas as possibilidades

In [32]:
# Gerando o design fatorial completo
design = doe.ff2n(4)

# Determinando o número de experimentos com base nas linhas da matriz de design
num_of_experiments = design.shape[0]

print(f"Número total de experimentos necessários: {num_of_experiments}")

Número total de experimentos necessários: 16


> **RESPOSTA:** 16

### Atividade 5.2: Crie um desenho fatorial fracionado
Crie um plano experimental para os fatores listados acima de forma que sejam testadas apenas 8 receitas:

**A) Quantidade de Fermento:**
24mg ou 36mg

**B) Temperatura:**
160ºC ou 180ºC

**C) Tempo:**
35min ou 40min

**D) Ovos:**
3 ou 4

In [33]:
# Gerando o design fatorial fracionado
# A string 'ABCD' representa os quatro fatores, sem considerar interações de alta ordem.
design_frac = doe.fracfact('A B C ABC')

# Convertendo o design para um DataFrame
df_frac = pd.DataFrame(design_frac, columns=["Fermento", "Temperatura", "Tempo", "Ovos"])

# Substituindo os valores para cada coluna com os valores reais
df_frac["Fermento"] = df_frac["Fermento"].replace({-1.0: "24mg", 1.0: "36mg"})
df_frac["Temperatura"] = df_frac["Temperatura"].replace({-1.0: "160ºC", 1.0: "180ºC"})
df_frac["Tempo"] = df_frac["Tempo"].replace({-1.0: "35min", 1.0: "40min"})
df_frac["Ovos"] = df_frac["Ovos"].replace({-1.0: "3", 1.0: "4"})

df_frac

Fermento Temperatura  Tempo Ovos
0     24mg       160ºC  35min    3
1     36mg       160ºC  35min    4
2     24mg       180ºC  35min    4
3     36mg       180ºC  35min    3
4     24mg       160ºC  40min    4
5     36mg       160ºC  40min    3
6     24mg       180ºC  40min    3
7     36mg       180ºC  40min    4

### Extra: Teste outras configurações, compare os dataframes gerados

Há várias maneiras de gerar os desenhos experimentais.
Sugestão: compare os dataframes utilizando a função `CONCAT` do pandas.

In [34]:
# Gerando o complemento do design fatorial fracionado
design_frac_complement = doe.fracfact('a b c -abc')

# Convertendo o design complementar para um DataFrame
df_frac_complement = pd.DataFrame(design_frac_complement, columns=["Fermento", "Temperatura", "Tempo", "Ovos"])

# Substituindo os valores para cada coluna com os valores reais
df_frac_complement["Fermento"] = df_frac_complement["Fermento"].replace({-1.0: "24mg", 1.0: "36mg"})
df_frac_complement["Temperatura"] = df_frac_complement["Temperatura"].replace({-1.0: "160ºC", 1.0: "180ºC"})
df_frac_complement["Tempo"] = df_frac_complement["Tempo"].replace({-1.0: "35min", 1.0: "40min"})
df_frac_complement["Ovos"] = df_frac_complement["Ovos"].replace({-1.0: "3", 1.0: "4"})

# Utilizando merge para identificar combinações que aparecem em ambos os dataframes (isso deve retornar um dataframe vazio)
common_rows = pd.merge(df_frac, df_frac_complement, how='inner')

print("Combinações comuns entre os dois designs (isso deve ser um dataframe vazio):")

common_rows


Combinações comuns entre os dois designs (isso deve ser um dataframe vazio):


Empty DataFrame
Columns: [Fermento, Temperatura, Tempo, Ovos]
Index: []

In [35]:
df_frac_complement

Fermento Temperatura  Tempo Ovos
0     24mg       160ºC  35min    4
1     36mg       160ºC  35min    3
2     24mg       180ºC  35min    3
3     36mg       180ºC  35min    4
4     24mg       160ºC  40min    3
5     36mg       160ºC  40min    4
6     24mg       180ºC  40min    4
7     36mg       180ºC  40min    3

In [ ]:
# seu código

In [ ]:
# seu código

### Desafio: Gere 2 dataframes complementares, de forma que não haja nenhuma repetição de linhas

In [ ]:
# seu código

In [ ]:
# seu código

In [ ]:
# seu código